# Generated by Django 5.1.6 on 2025-03-31 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
