# Generated by Django 5.1.6 on 2025-04-01 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_remove_cart_products_remove_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='comments.cartitem'),
        ),
    ]
