# Generated by Django 5.1.6 on 2025-04-01 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
